dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install: pip install -r requirements.txt
script: python -c "from steamapi import *"

jobs:
  include:
    - stage: "Code quality"
      install:
        - pip install -r requirements.txt
        - pip install pycodestyle
      name: "PEP-8"
      python: "3.7"
      script: python -m pycodestyle --ignore=E501,E741 ./steamapi
